# Generated by Django 3.2 on 2024-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='organization',
            field=models.CharField(default='AMFB', max_length=5),
        ),
    ]
