# Generated by Django 3.2 on 2024-10-28 08:07

from django.db import migrations, models
import managers


class Migration(migrations.Migration):

    dependencies = [
        ('alertmfb', '0002_alter_accountopening_account_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountopening',
            name='account_file',
            field=models.FileField(upload_to='account_files', validators=[managers.acct_file_size]),
        ),
    ]
